### ISSUE TITLE
wildtype is not guaranteed to have a functional score or latent effect of zero

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#73]
This may be OK, but I think if this is a design choice it should be explicitly discussed as some global epistasis models (eg, Otwinoski et al) ensure that wildtype has a value of zero on both the latent effect and functional score scale (in this case, for the wildtype).

If we are not doing this, it should be clearly discussed in the documentation.

Also, we should check if the lack of this constraint introduces identifiability issues for any of the global epistasis model forms.

**Comment by jbloom** [comment]
I'm also not entirely sure if we need to do this at all. It could be that there *is* an identifiability issue for the splines used by Otwinoski (I'm pretty sure there is in their case?) but there isn't for the sigmoids. (But is there for any of other models?). In that case, if we do this as post-processing maybe it is not a good idea as it would make the fit worse?

Mostly I think we should:

 - be clear in text (methods) and docs about whether or not wildtype can have non-zero latent phenotype / predicted functional score
- for single mutants, report the *change* in latent phenotype / predicted functional score relative to wildtype rather than absolute value. Note that this is already correct for `mutations_df` and latent phenotype as `beta` essentially represents delta of latent phenotype from wildtype, but if we augment that method to report mutation predicted functional scores we should make sure that they are in fact deltas from wildtype, and also perhaps explain all of this a bit more clearly in API and overall example docs?

**Comment by jgallowa07** [comment]
Agreed! I'll be sure to clarify on my next pass through the example docs.

**Comment by jgallowa07** [comment]
@jbloom @Haddox I'm testing a sweep of models where we _only_ have the condition(experiment)-specific bias term added to each non reference latent prediction, dubbed \beta_0^{(d)}, and no $\beta_0$ which is not experiment specific and is added to all predictions. These two terms introduce redundancy when they are both included, and if the fits look good then we can be sure the reference experiment wildtype is locked at zero. I'll follow up when the models finish, but let me know if you think this is a bad idea and $\beta_0$ is indeed something we want to keep in the model.

**Comment by jbloom** [comment]
I'm trying to look at the formula, and I think this does fundamentally remove a parameter from the fitting (consider the case for the reference condition). Essentially, removing `beta_0` forces the wildtype to be at the midpoint of the sigma, which we probably do not want.

I think that this would be solved by moving `beta_0` to be a term in the global epistasis function:
`g(z) = alpha_scale / (1 + exp(-z - beta_0) + alpha_bias`

However, above is basically mathematically equivalent. I think it is fine to keep as it is, if we are just explicit in the documentation that neither wildtype latent nor predicted functional score are guaranteed to be zero?

**Comment by jgallowa07** [comment]
Good point - I had forgot there was no x-axis free parameter for the sigmoid. Although, I guess I'm curious if there's any reason we wouldn't just give the reference experiment it's own free $\beta_0^{(d)}$ param -- But there's more important things at hand so I'll keep things as they are and update the docs. In that case, the final latent model equation (in the main text, as well as in the docs) should then be:

$$
\phi_{d}(v) = \beta_0 +  \beta_0^{(d)} + \sum_{m \in v}(\beta_m + \Delta_{d,m})
$$

**Comment by jbloom** [comment]
I think giving the reference it's own free `beta_0^d` would basically be equivalent to what we are doing now if we removed the constraint that `beta_0^d = 0` for reference, right?

**Comment by Haddox** [comment]
I agree that we should impose the constraint `beta_0^d = 0` when d is the reference experiment. This is what we did in the current fits, right?

If we removed this constraint, then I agree that `beta_0^d` would be redundant with `beta_0` when d is the reference. But, I think our current model is fine as long as we impose the constraint.

Also, I wonder if it might be better to call `beta_0^d` something else. To me, that notation makes it seem like it's the latent phenotype for the wildtype sequence from experiment `d`. Instead, it helps capture the effects of mutations in "the bundle" that aren't measured in the DMS experiment and so don't have beta and shift parameters (e.g., indels between the spike homologs).

**Comment by WSDeWitt** [comment]
- I agree it's equivalent to have the intercept term appear in the latent phenotype or in the nonlinearity, as @jbloom shows above.
- It's probably more standard to do the former, since that's how neural networks and generalized linear models are defined. We're used to seeing "bias terms" (along with the weights) in the linear components, and nonlinear activations that map the origin to a fixed value (typically itself or 0.5).
- I agree that the nonlinearities have slightly too much flexibility, because they don't fix the latent=0 sequence to have score=0 (or any other specific value). The limitation this creates is that we have no way of enforcing WT-referenced functional scores in the reference experiment, because even if we fix $\\beta^{\text{ref}}_0 = 0$ (so reference WT has latent=0), that doesn't pin down the predicted WT score to any specific value as we vary the parameters of the nonlinearity. So for this reason I agree with the overall point of this issue. I remember this is something we talked about a while ago, and there was a decision to do what we are currently doing, but I don't remember the reasoning.
- The [current docs](https://matsengrp.github.io/multidms/biophysical_model.html#Additive-latent-phenotype) have two latent intercept terms in each experiment $d$: $\phi_d(v) = \\beta_0 + \\beta^d_0 + \\sum_{m \\in v} (\\beta_{m} + \\Delta_{d, m})$. I think there's no need for both of these intercepts, because we can always absorb $\\beta_0$ into $\\beta^d_0$, so there's no information allowing us to additionally infer $\\beta_0$. In some settings (such as our main text), we want to enforce that the intercepts are equal across experiments. Then it makes sense to simplify the way we present the model to only have $\\beta_0$, as in the current main text equation. But I don't think we should ever write the equation with both $\\beta_0$ and $\\beta^d_0$, or introduce these as if they are distinct parameters. For the more general setup in the docs, we could have only $\\beta^d_0$, and allow for optional constraints on it.

**Comment by Haddox** [comment]
I think something like $\beta_0^d$ is needed if there are mutations that separate the wildtype sequences of two homologs that aren't measured in the DMS experiment. For instance, there a multiple indels that separate the Delta and BA.1 wildtype sequences. We do not estimate beta or shift parameters for these indel mutations, so in the scenario where BA.1 is the reference, the effects of these indels are not accounted for in the summation term when computing the latent phenotype of Delta's wildtype sequence. In the case of Delta and BA.1, having something like $\beta_0^d$ helps capture the missing effects for all such mutations.

**Comment by jgallowa07** [comment]
> I think giving the reference it's own free beta_0^d would basically be equivalent to what we are doing now if we removed the constraint that beta_0^d = 0 for reference, right?

@jbloom Correct

> I agree that we should impose the constraint beta_0^d = 0 when d is the reference experiment. This is what we did in the current fits, right?

@Haddox Correct, but to be clear - removing this constraint of $\beta_0^d = 0$, as well as removing the $\beta_0$ param all together would be functionally the same. That being said, I think your comment above gives motivation for keeping both around and keeping things the way they are.

> For the more general setup in the docs, we could have only $\beta^{(d)}_0$, and allow for optional constraints on it.
Agreed! 

So, I think we all in agreement that we leave the actual model and fits as they are (using both $\beta_0$ and ref constrained $\beta^{(d)}_0$). 

With regard to the ms and docs, I think I agree with @WSDeWitt that don't need both params. That being the case I think it's fine to stick with $\beta_0$ for both - especially as $\beta^{(d)}_0$ is an optional feature in `multidms`

**Comment by Haddox** [comment]
> @Haddox Correct, but to be clear - removing this constraint of 
> , as well as removing the 
>  param all together would be functionally the same. That being said, I think your comment above gives motivation for keeping both around and keeping things the way they are.
I agree.

But, I do think that both $beta_0$ and $beta_0^d$ are important. Both have clear interpretations:
* $beta_0$ is the intercept parameter that defines the latent phenotype of the wildtype sequence from the reference experiment.
* $beta_0^d$ is an offset parameter that captures the effects of mutations in "the bundle" that aren't measured in the experiment, which should be included in the summation term, but aren't because we don't have parameter estimates. $beta_0^d$ essentially sums up all the betas and shifts for those missing mutations. So, I'm not sure if it's correct to think of $beta_0^d$ as an intercept term in the same way as $beta_0$, which is why I think it may be nice to use a different variable name that doesn't have $beta$ in it. After all, it should be capturing a sum of betas and shifts.

**Comment by jgallowa07** [comment]
Great points - I agree with all. But to make sure I’m clear, you think both should be included in both equations (ms and docs)?

**Comment by WSDeWitt** [comment]
Just to clarify, do you define/enforce $\beta_0^d = 0$ when $d=\text{ref}$? I agree we need $\beta_0^d$ for $d \ne \text{ref}$ for the reasons you say. But it might be tidier to just define \beta_0^{\text{ref}} = \beta_0$, and keep all of these offset terms in that one vector. I think this is the same as what Jesse suggested a few posts above (sorry I was posting somewhat out-of-sync because I hadn't refreshed in a bit).

Do you think it's an issue that the nonlinearity doesn't keep the latent=0 sequence at a fixed value in the reference experiment?

**Comment by jgallowa07** [comment]
Correct about the beta ref constraint. And I would be okay with either combining into a single beta_0 as will suggests, or making up a different term that clarifies the difference, as hugh suggests. I’ll let y’all decide just lmk what you decide and I’ll update the docs

**Comment by WSDeWitt** [comment]
Hugh's suggestion of using a different variable does seem better notationally aligned with how we currently treat the mutation effect parameters as WT + bundle-induced shift.

**Comment by jgallowa07** [comment]
Makes sense to me! Any suggestions?

**Comment by WSDeWitt** [comment]
I'll leave it to @Haddox to decide, but if it was, say, $\delta_d$ we could then define the model in terms of shifts wrt ref like so:

$$
\begin{align*}
\phi_\text{ref}(v) &= \beta_0 + \sum_{m\in v}\beta_m\\
\phi_d(v) &= \phi_\text{ref}(v) + \delta_d + \sum_{m\in v}\Delta_{d,m}, \quad d\ne \text{ref}
\end{align*}
$$

**Comment by Haddox** [comment]
Thanks @WSDeWitt, that's an interesting idea to split it up. I just spoke with Erick, and we came up with:

$$
\begin{align*}
\phi_d(v) &= \beta_0 + \alpha_d + \sum_{m\in v}(\beta_m+\Delta_{d,m})\\
\end{align*}
$$

where alpha is the offset parameter for each experiment d and should be fixed to zero when d is the reference. Part of me likes this version since it closely mirrors the equation in the main text, which I assumed we're keeping as is. 

I also like your version, though I'd suggest using something like alpha instead of $\Delta_{d,0}$ since the offset parameter add up not only shifts but also betas for mutations missing from the bundle. For that reason, maybe it's best to include everything in one equation so it doesn't look like it's just an offset term for the shifts? But if you prefer your two-equation version, then I'm happy to go with that, too.

**Comment by WSDeWitt** [comment]
Using $\alpha$ for the indel/bundle shift parameters is fine, but then we should change the nonlinearity params in docs, which are currently $\alpha$. The main text uses $\theta$ for the nonlinearity, so probably good to go with that.

I guess I slightly favor presenting the split equation in the main text, since it manifests the standard GE model first, and then the shifts are presented in a way that avoids the appearance of identifiability issues. But ok with me either way.

**Comment by Haddox** [comment]
The manifestation of the standard GE model is nice. But, in the end, I think I prefer the one-liner since it's clearer that $\alpha_d$ is capturing both missing betas and shifts, not just shifts. So if it's my call, I say we go with the one-liner with $\alpha_d$ and change the nonlinearity parameters in the docs from $\alpha$ to $\theta$. Thanks @jgallowa07 and @WSDeWitt!

**Comment by Haddox** [comment]
> Do you think it's an issue that the nonlinearity doesn't keep the latent=0 sequence at a fixed value in the reference experiment?

@WSDeWitt: I don't think this is an issue, at least with the sigmoid, based on the constraints we put on it? We don't allow the sigmoid to move to the left or right or expand/contract on the x-axis. So, $\beta_0$ is the only parameter that determines the position of the reference experiment's wildtype sequence along the x-component of the sigmoid. The sigmoid can then move up and down or expand/contract on the y-axis to make sure that it matches the range of observed functional scores, and puts the wildtype sequence and others in the right place along the y-axis. So the wildtype sequence from the reference experiment should be pinned to a single "correct" location on the sigmoid, where its position on the y-axis is determined by its functional score and its position on the x depends on the global epistasis in the data. All parameters are identifiable in this scenario, right? Or did I misunderstand your question?

**Comment by WSDeWitt** [comment]
@Haddox What I have in mind is the setting where we know, by definition, that the WT seq has score=0, such as for relative enrichments in the reference experiment, or for phenotypes like affinity/expression that are relative to measurements on WT. The question is how does our model reflect this "by definition"—does it have to learn this from the data? I think in the current setup the model would have to learn this from the data, because, even if we set $\beta_0=0$ to fix the WT latent=0, different values of the sigmoid parameters will give different predictions for the WT score. Tuning the parameters is needed for a correct WT prediction. In this sense, it could be said that the nonlinearity is a bit too flexible, since in general it predicts the WT seq in the reference experiment to be nonzero when we know _a priori_ that it is exactly zero (although it has the ability to learn _a posteriori_ that it should predict near zero).

Does that make sense, or do I have it wrong?

**Comment by Haddox** [comment]
Got it! Yes, I agree with everything you said. Seems like in practice it has been able to learn this in the spike and other datasets we've analyzed, as long as the parameters were initialized at reasonable starting values. But would be neat to have a fitting protocol where it didn't have to learn this if that would help speed things up, which you could turn on if your experiment matched the setting you described.

**Comment by WSDeWitt** [comment]
If we wanted to incorporate this as an option, I think it is straightforward. To make the nonlinearity pass through the origin, we can just shift it to $g(z)\leftarrow g(z) - g(0)$.

**Comment by Haddox** [comment]
Sounds good. I put this on our to-do list for after submitting the paper if that sounds good to you.

**Comment by jbloom** [comment]
Not to interject too much, but I feel like if the major part of the paper is the software, we should probably have the software finalized (at at least some versioned state) before submitting the paper. Don't we want the model specified in the paper and software to match?

**Comment by WSDeWitt** [comment]
I agree a release needs to be cut for submission, and referenced in the ms. Erick has issue #69 with various presubmission software tidying tasks, and we could add this.

If this issue is seen as an important problem that needs resolution, that should come first too (but I think Hugh is saying it's not).

**Comment by Haddox** [comment]
Thanks Jesse and Will. Agreed. We will be sure to have the software in a finalized version state before submitting the paper. Will's suggestion is a good one, but I think we can wait to include it as an optional feature in a future version as the software package evolves.

**Comment by jgallowa07** [comment]
@jbloom @Haddox @WSDeWitt Thanks for all the help here. My latest updates included a post processing approach to reporting phenotypic effects wrt their delta WT. I'm going to close this for now. This has been documented and does not conflict with what we report in the MS in any way. Please feel free to open if you feel otherwise.
